### PR TITLE
Reorganize into one package

### PR DESCRIPTION
**Pull request by tysongach**
Having each component be a unique npm package creates a lot of
maintenance overhead for little to no gain. This reorganizes the project
into one npm package.

- All styles have been moved from a `packages/` directory, to `src/`,
  since they are no longer individual "packages"
- The primary package is now named `@thoughtbot/design-system`
- The `support` styles have been renamed `settings`
- Consumers can replace their Sass imports, from individual imports to
  one bulk import:

    ```diff
    -@import "@thoughtbot/tbds-button/index";
    -@import "@thoughtbot/tbds-forms/index";
    +@import "@thoughtbot/design-system/src/index";
    ```

Closes https://github.com/thoughtbot/design-system/issues/48

### CODE REVIEW

**Comment by setphen** [comment]
Is it possible to structure (or link) the package in a way that it can be imported with a shorter path?
```diff
-@import "@thoughtbot/design-system/src/index";
+@import "@thoughtbot/design-system";
```

**Comment by tysongach** [comment]
> Is it possible to structure (or link) the package in a way that it can be imported with a shorter path?

That’s a great question. I don’t believe there is without writing and adding code which would “build” the package before publishing to npm. For example, it could move everything in `src` up to the root level of the package, therefore removing `src/` from the import path.

I felt like this is an optimization we could do in the future. I was a bit hesitate to go down the path because it would require meta code to be maintained that doesn’t impact the consumer experience, too much.

**Comment by setphen** [comment]
What are your thoughts about the pattern Bourbon uses? The root is in `bourbon/core/_bourbon.scss`  which allows more concise imports, as long as the build tool knows where the path is:

```
        includePaths: [
          "node_modules/bourbon/core/"
        ]
```

```
@import "bourbon";
```

---

So, if the main "index" became "tbds" we could do:


```
        includePaths: [
          "node_modules/@thoughtbot/design-system/src"
        ]
```

```
@import "tbds";
```

Maybe I'm overthinking this.

**Comment by tysongach** [comment]
> Maybe I'm overthinking this.

Nope!

`includePaths` is a great idea, but it’s specific to Node environments and tooling that uses node-sass. So a Rails project, for example, wouldn’t get that benefit. One thing I’ve struggled with on Bourbon is supporting specific installation methods for each framework/environment. It becomes a headache quickly. My thinking with a build step would be to have the package itself as flat and simple as possible, and not add tooling for specific frameworks.

**Comment by tysongach** [comment]
@setphen I went ahead and merged, but let's keep discussed how we can improve the importing!

**Pull request merged**
